Repository devopsgym/environment-chinmangrove-staging, pull requests merged in 2019-08, with the labels that each got.

#1 chore: springprojectnew to 0.0.1
  env/Chart.yaml
  env/requirements.yaml
Labels: size/S

#2 chore: springprojectnew to 0.0.2
  env/requirements.yaml
Labels: size/XS

#3 chore: springprojectnew to 0.0.3
  env/requirements.yaml
Labels: size/XS

#4 chore: springprojectnew to 0.0.4
  env/requirements.yaml
Labels: size/XS

#5 Update requirements.yaml
  env/requirements.yaml
Labels: needs-ok-to-test, size/XS

#7 chore: jx-go-loops to 0.0.2
  env/requirements.yaml
Labels: size/XS
